// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7e0OFY0B7Xr69I42Awshsyk16BFnpmMM',
    appId: '1:356788851461:web:08f1b0333985f5ad74dd6c',
    messagingSenderId: '356788851461',
    projectId: 'grocar-380e1',
    authDomain: 'grocar-380e1.firebaseapp.com',
    databaseURL:
        'https://grocar-380e1-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'grocar-380e1.appspot.com',
    measurementId: 'G-Q71TTR4F0W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLSYPykWw4ucWKxEox9h5a_OWTmpu9izI',
    appId: '1:356788851461:android:45513306d54df51474dd6c',
    messagingSenderId: '356788851461',
    projectId: 'grocar-380e1',
    databaseURL:
        'https://grocar-380e1-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'grocar-380e1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbdQwb6VfXavifP-0BJrCgIUJgScQLVBs',
    appId: '1:356788851461:ios:ae815eeb48e5ea7674dd6c',
    messagingSenderId: '356788851461',
    projectId: 'grocar-380e1',
    databaseURL:
        'https://grocar-380e1-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'grocar-380e1.appspot.com',
    androidClientId:
        '356788851461-uo4nvksqit8s32ka4dgp7el168o3n3n7.apps.googleusercontent.com',
    iosClientId:
        '356788851461-ck3kic4f42cqv804tgl2q7irgvj7q1il.apps.googleusercontent.com',
    iosBundleId: 'eg.edu.miuegypt.csc422.grocar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbdQwb6VfXavifP-0BJrCgIUJgScQLVBs',
    appId: '1:356788851461:ios:ae815eeb48e5ea7674dd6c',
    messagingSenderId: '356788851461',
    projectId: 'grocar-380e1',
    databaseURL:
        'https://grocar-380e1-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'grocar-380e1.appspot.com',
    androidClientId:
        '356788851461-uo4nvksqit8s32ka4dgp7el168o3n3n7.apps.googleusercontent.com',
    iosClientId:
        '356788851461-ck3kic4f42cqv804tgl2q7irgvj7q1il.apps.googleusercontent.com',
    iosBundleId: 'eg.edu.miuegypt.csc422.grocar',
  );
}
